matching_groups:
      - /user/.+/gacha/.+
      - /user/.+/present/.+
      - /user/.+/card
      - /user/.+/card/.+
      - /user/.+/home
sort: avg
reverse: true
metrics:
  - count
  - method
  - uri
  - min
  - avg
  - max
  - sum
file: /var/log/nginx/access.log